# Generated by Django 5.0.1 on 2024-02-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aut_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_roles',
        ),
        migrations.AddField(
            model_name='user',
            name='autType',
            field=models.CharField(choices=[('via_email', 'Via Email'), ('via_phone', 'Via Phone'), ('via_username', 'Via Username')], default='via_username', max_length=31),
        ),
        migrations.AddField(
            model_name='user',
            name='userRoles',
            field=models.CharField(choices=[('ordinary_user', 'Ordinary User'), ('manager', 'Manager'), ('super_admin', 'Super Admin')], default='ordinary_user', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=15, null=True),
        ),
    ]
