# Generated by Django 5.0.2 on 2024-02-20 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_user_aut_type_remove_user_user_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='autType',
            field=models.CharField(choices=[('VIA_EMAIL', 'Via Email'), ('VIA_PHONE', 'Via Phone'), ('VIA_USERNAME', 'Via Username')], default='VIA_USERNAME', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userRoles',
            field=models.CharField(choices=[('ORDINARY_USER', 'Ordinary User'), ('MANAGER', 'Manager'), ('SUPER_ADMIN', 'Super Admin')], default='ORDINARY_USER', max_length=31),
        ),
        migrations.CreateModel(
            name='UserConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('verifyType', models.CharField(choices=[('VIA_EMAIL', 'Via Email'), ('VIA_PHONE', 'Via Phone')], max_length=31, null=True)),
                ('expirationTime', models.DateTimeField(null=True)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
